import fs from "node:fs/promises";
import path from "node:path";
import { config } from "@/lib/config";
import { characterLibrarySchema, type Character } from "@/lib/schemas/character";

/**
 * Durable JSON store for the global character library.
 *
 * Projects live in the in-memory repository because a demo session is
 * disposable. The character library is not: it is configuration the user
 * curates once and expects to still be there tomorrow, so it is written to disk
 * under the data directory. The file is small (tens of records at most), so a
 * read-modify-write of the whole document is simpler and safer than partial
 * updates.
 */

const LIBRARY_DIRNAME = "library";
const LIBRARY_FILENAME = "characters.json";
const REFERENCE_DIRNAME = "character-images";

export function libraryDir(): string {
  return path.resolve(process.cwd(), config.dataDir, LIBRARY_DIRNAME);
}

export function referenceImageDir(): string {
  return path.join(libraryDir(), REFERENCE_DIRNAME);
}

/**
 * Resolve a stored reference-image filename to an absolute path, rejecting
 * anything that escapes the library root. Filenames are generated by this
 * module, but the check keeps a tampered library file from turning into an
 * arbitrary-file-read primitive.
 */
export function resolveReferenceImagePath(filename: string): string | null {
  const root = referenceImageDir();
  const resolved = path.resolve(root, filename);
  const rel = path.relative(root, resolved);
  if (rel.startsWith("..") || path.isAbsolute(rel)) return null;
  return resolved;
}

const libraryFile = () => path.join(libraryDir(), LIBRARY_FILENAME);

/**
 * Serialises writes. Next.js route handlers run concurrently in one process, so
 * two simultaneous saves would otherwise read the same snapshot and the second
 * would clobber the first.
 */
const globalRef = globalThis as unknown as { __storyforgeCharacterLock?: Promise<unknown> };

async function withLock<T>(fn: () => Promise<T>): Promise<T> {
  const previous = globalRef.__storyforgeCharacterLock ?? Promise.resolve();
  const run = previous.then(fn, fn);
  globalRef.__storyforgeCharacterLock = run.catch(() => undefined);
  return run;
}

async function readLibrary(): Promise<Character[]> {
  try {
    const raw = await fs.readFile(libraryFile(), "utf8");
    const parsed = characterLibrarySchema.safeParse(JSON.parse(raw));
    return parsed.success ? parsed.data.characters : [];
  } catch {
    // Missing or unreadable file means an empty library, not an error: a fresh
    // install has no data directory yet.
    return [];
  }
}

async function writeLibrary(characters: Character[]): Promise<void> {
  await fs.mkdir(libraryDir(), { recursive: true });
  const payload = characterLibrarySchema.parse({ version: 1, characters });
  await fs.writeFile(libraryFile(), `${JSON.stringify(payload, null, 2)}\n`, "utf8");
}

export const characterStore = {
  async list(): Promise<Character[]> {
    const characters = await readLibrary();
    return [...characters].sort((a, b) => a.name.localeCompare(b.name));
  },

  async get(id: string): Promise<Character | null> {
    const characters = await readLibrary();
    return characters.find((c) => c.id === id) ?? null;
  },

  /** Resolve many ids at once, preserving the caller's ordering and skipping unknown ids. */
  async getMany(ids: readonly string[]): Promise<Character[]> {
    if (ids.length === 0) return [];
    const characters = await readLibrary();
    const byId = new Map(characters.map((c) => [c.id, c]));
    return ids.map((id) => byId.get(id)).filter((c): c is Character => c !== undefined);
  },

  async save(character: Character): Promise<Character> {
    return withLock(async () => {
      const characters = await readLibrary();
      const index = characters.findIndex((c) => c.id === character.id);
      if (index >= 0) characters[index] = character;
      else characters.push(character);
      await writeLibrary(characters);
      return character;
    });
  },

  async remove(id: string): Promise<boolean> {
    return withLock(async () => {
      const characters = await readLibrary();
      const next = characters.filter((c) => c.id !== id);
      if (next.length === characters.length) return false;
      await writeLibrary(next);
      return true;
    });
  },

  async writeReferenceImage(filename: string, bytes: Buffer): Promise<void> {
    const target = resolveReferenceImagePath(filename);
    if (!target) throw new Error("Invalid reference image filename");
    await fs.mkdir(referenceImageDir(), { recursive: true });
    await fs.writeFile(target, bytes);
  },

  async deleteReferenceImage(filename: string): Promise<void> {
    const target = resolveReferenceImagePath(filename);
    if (!target) return;
    await fs.rm(target, { force: true });
  },
};
