import { z } from "zod";

/** Dialogue line used in scenes and audio cues (spec Section 6.4 / 2A.7). */
export const dialogueLineSchema = z.object({
  character: z.string(),
  line: z.string(),
});
export type DialogueLine = z.infer<typeof dialogueLineSchema>;

/**
 * Casting direction for spoken content.
 *
 * Dialogue and narration are performed by the video model (LTX-2 renders speech
 * from the scene prompt), so this is prompt direction, not a TTS voice config.
 */
export const voiceProfileSchema = z.object({
  id: z.string(),
  name: z.string(),
  role: z.enum(["narrator", "character", "host", "announcer"]),
  voiceDescription: z.string(),
  accent: z.string().optional(),
  pacing: z.string().optional(),
  emotion: z.string().optional(),
});
export type VoiceProfile = z.infer<typeof voiceProfileSchema>;

/**
 * Per-scene audio intent. Spoken content here is folded into the scene's video
 * prompt; music/SFX intent is refined into timed `AudioCue`s.
 */
export const sceneAudioCueSchema = z.object({
  sceneId: z.string(),
  narrationText: z.string().optional(),
  dialogueLines: z.array(dialogueLineSchema).optional(),
  musicCue: z.string().optional(),
  sfxCues: z.array(z.string()).optional(),
});
export type SceneAudioCue = z.infer<typeof sceneAudioCueSchema>;

export const AUDIO_CUE_KINDS = ["music", "sfx"] as const;
export const audioCueKindSchema = z.enum(AUDIO_CUE_KINDS);
export type AudioCueKind = (typeof AUDIO_CUE_KINDS)[number];

/**
 * A generated music/SFX bed laid over the cut.
 *
 * Timing is authored relative to its anchor scene and resolved to an absolute
 * timeline offset at assembly, so regenerating or re-trimming another scene
 * never invalidates the cue.
 *
 * `duckNativeDb` is the single mixing control: 0 leaves the clip's own audio
 * untouched (additive SFX), -12 pushes it under a music bed, and -60 is an
 * effective replace.
 */
export const audioCueSchema = z.object({
  id: z.string(),
  sceneId: z.string(),
  kind: audioCueKindSchema,
  /** Prompt for the WanGP audio model. */
  prompt: z.string(),
  /** Offset from the start of the anchor scene. */
  startSeconds: z.number().nonnegative(),
  durationSeconds: z.number().positive(),
  gainDb: z.number().default(-6),
  fadeInSeconds: z.number().nonnegative().default(0.5),
  fadeOutSeconds: z.number().nonnegative().default(0.5),
  duckNativeDb: z.number().max(0).default(0),
  modelType: z.string().optional(),
  generatedPath: z.string().optional(),
  approved: z.boolean().default(false),
  createdAt: z.string().optional(),
});
export type AudioCue = z.infer<typeof audioCueSchema>;

/** Project-level audio plan (spec Section 2A.7). */
export const audioPlanSchema = z.object({
  projectId: z.string(),
  narrationRequired: z.boolean(),
  dialogueRequired: z.boolean(),
  musicRequired: z.boolean(),
  sfxRequired: z.boolean(),
  voiceProfiles: z.array(voiceProfileSchema),
  sceneAudioCues: z.array(sceneAudioCueSchema),
  /** Timed music/SFX beds generated by StoryForge and mixed into the cut. */
  cues: z.array(audioCueSchema).default([]),
  musicDirection: z.string().optional(),
  sfxLibraryNotes: z.string().optional(),
});
export type AudioPlan = z.infer<typeof audioPlanSchema>;

/** Animatic frame + plan (spec Section 2A.5 / 14.7). */
export const animaticFrameSchema = z.object({
  sceneNumber: z.number().int().positive(),
  caption: z.string(),
  durationSeconds: z.number().int().positive(),
  transitionIn: z.string(),
  transitionOut: z.string(),
  startFramePrompt: z.string(),
  endFramePrompt: z.string(),
});
export type AnimaticFrame = z.infer<typeof animaticFrameSchema>;

export const animaticPlanSchema = z.object({
  projectId: z.string(),
  totalDurationSeconds: z.number().int().nonnegative(),
  frames: z.array(animaticFrameSchema),
  sceneDurationMap: z.record(z.number()),
  previewAssembled: z.boolean(),
  previewPath: z.string().optional(),
});
export type AnimaticPlan = z.infer<typeof animaticPlanSchema>;
